version: 0.2

env:
  #variables:
     # key: "value"
  parameter-store:
     K8SKEY: "symkey-k8s-nonprod-env"
     
    

phases:
  install:
    commands:
       - "apt update"
       - "apt install -y awscli git"
       - "wget https://github.com/kubernetes/kops/releases/download/1.8.0/kops-linux-amd64"
       - "chmod +x kops-linux-amd64"
       - "mv kops-linux-amd64 /usr/local/bin/kops"
       - "curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
       - "chmod +x kubectl"
       - "mv ./kubectl /usr/local/bin/kubectl"
       - "wget https://storage.googleapis.com/kubernetes-helm/helm-v2.8.2-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz"
       - "chmod +x ./linux-amd64/helm"
       - "mv ./linux-amd64/helm /usr/local/bin/helm"
       - "apt-get install gnupg"
       - "git init"
       - "git clone https://github.com/ministryofjustice/k8s-nonprod-environments.git"
       - "cd k8s-nonprod-environments"
       - "ls -la"
       - "git clone https://github.com/AGWA/git-crypt.git"
       - "cd git-crypt"
       - "make"
       - "make install PREFIX=/usr/local"
       - "cd .."
       - "pwd"
       - "ls -la"
      #  - "git init"
  pre_build:
    commands:
      - "mkdir ~/.kube/"
      - "echo $K8SKEY | base64 --decode > ~/private.key"
      - "git checkout add-git-crypt"
      - "pwd"
      - "ls -la"
      # - "git branch -a"
      # - "gpg --list-keys"
      # - "echo $kubernetes-key-pw | gpg --batch --yes --import ~/private.key"
      # - "gpg --list-keys"
      - "git-crypt unlock ~/private.key"
      - "cat cluster-authentication.key"
      - "cp cluster-authentication.key ~/.kube/config"
      - "cat ~/.kube/config"
      - "rm ~/private.key"
      # - "aws s3 cp s3://non-production-cluster-keystore/kubecfg.yaml ~/.kube/config" 
  build:
    commands:
      - "kubectl config get-contexts"
      - "kubectl config use-context non-production.k8s.integration.dsd.io"
      - "kubectl cluster-info"
      - "kubectl get namespaces"
      - "kubectl get pods --all-namespaces"
      - "ls namespaces/ | while read file; do kubectl create -f namespaces/$file/namespace.yaml; kubectl apply -f namespaces/$file --namespace=$file; done"
#     - "kubectl delete namespaces dev"

  post_build:
    commands:
#       - "ls namespaces/ | while read file; do helm init --service-account $file-tiller --tiller-namespace $file; done"

#artifacts:
  #files:
    # - location
  #discard-paths: yes
  #base-directory: location

#cache:
  #paths:
    # - paths
