apiVersion: v1
kind: ServiceAccount
metadata:
  name: circleci
  namespace: cloudplatforms-reference-app

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: cloudplatforms-reference-app
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "list"
  - apiGroups:
      - ""
    resources:
      - "pods/portforward"
    verbs:
      - "create"
  - apiGroups:
      - "extensions"
    resources:
      - "deployments"
    verbs:
      - "create"

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: circleci
  namespace: cloudplatforms-reference-app
subjects:
- kind: ServiceAccount
  name: circleci
  namespace: cloudplatforms-reference-app
roleRef:
  kind: Role
  name: circleci
  apiGroup: rbac.authorization.k8s.io
